# Generated by Django 5.0.6 on 2024-06-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='survey', max_length=255),
            preserve_default=False,
        ),
    ]
