# Generated by Django 5.0.6 on 2024-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
    ]
