# Generated by Django 5.0.6 on 2024-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ms_options',
            field=models.JSONField(default=None, null=True),
        ),
    ]
